import type {
  AIProvider,
  TextGenerationRequest,
  StructuredGenerationRequest,
} from "./types.js";

export class MockProvider implements AIProvider {
  name = "mock";

  async generateText(request: TextGenerationRequest): Promise<string> {
    const system = request.systemPrompt.toLowerCase();
    const user = request.userPrompt.toLowerCase();
    const combined = user + system;
    const targetPath = user.match(/generate only the content for:\s*([^\n]+)/)?.[1]?.trim() || "";
    const target = targetPath || combined;

    if (target.includes("project_brief") || target.includes("project brief")) {
      return `# Project Brief\n\n## Summary\nA sample project generated by mock provider.\n\n## Target users\nDevelopers and technical teams.\n\n## Problem\nSetting up projects for AI agents is repetitive.\n\n## Proposed solution\nUse AgentOS to generate structured project context.\n\n## MVP outcome\nWorking CLI that produces docs and skills.\n\n## Known constraints\n- TypeScript/Node.js\n- OpenAI API\n- No static templates\n\n## Explicit non-goals\n- Hosting management\n- Full app scaffolding\n\n## Open questions\n- Pricing model\n\n## Agent guidance\nRead docs/agentos/ before implementing.`;
    }
    if (target.includes("product_requirements") || target.includes("requirements")) {
      return `# Product Requirements\n\n## Product overview\nAgentOS generates AI-ready project documentation.\n\n## Personas\n- Indie builders\n- Technical founders\n\n## User stories\n- As a builder, I want to run one command so that my project has agent-ready docs.\n\n## Functional requirements\n1. Generate project brief\n2. Generate PRD\n3. Generate architecture doc\n4. Generate implementation plan\n\n## Non-functional requirements\n- Deterministic schema validation\n- Secret redaction\n\n## MVP scope\nCLI init, brief, refine, doctor, skill pack.\n\n## Out-of-scope items\nHosted SaaS, local LLMs, deployment management.\n\n## Acceptance criteria\n- All required files generated\n- doctor passes\n- Mock tests pass\n\n## Edge cases\n- Missing API key\n- Existing files\n\n## Questions for human review\n- Default model selection`;
    }
    if (target.includes("architecture")) {
      return `# Architecture\n\n## Architecture summary\nTypeScript CLI using OpenAI Responses API with structured outputs.\n\n## Recommended stack\n- Node.js 20+\n- TypeScript\n- OpenAI SDK\n- Commander.js\n\n## Data model assumptions\nProjectProfile, ArtifactPlan, and per-document schemas.\n\n## Main modules\n- CLI routing\n- Provider abstraction\n- Generation pipeline\n- File writers\n- Validators\n\n## Integration points\n- OpenAI API\n- File system\n\n## State management\nStateless CLI; config stored in .agentos/config.json.\n\n## Error handling\nStructured errors with fix guidance.\n\n## Security considerations\n- Redact secrets before API calls\n- Never write API keys to generated files\n\n## File structure recommendation\nsrc/ organized by domain: commands, provider, generation, writers, validators.\n\n## Architecture tradeoffs\n- Multi-pass AI generation costs tokens but improves quality.\n- Mock provider enables testing without API keys.\n\n## What not to overbuild\nNo plugin marketplace, no hosted web UI in MVP.`;
    }
    if (target.includes("implementation_plan") || target.includes("implementation plan")) {
      return `# Implementation Plan\n\n## Phase 0: setup and verification\n- Initialize TypeScript project\n- Add dependencies\n- Verify build and test pipeline\n\n## Phase 1: core data model\n- Define schemas (ProjectProfile, ArtifactPlan)\n- Implement provider interface\n- Implement mock provider\n\n## Phase 2: core user flow\n- Implement init command\n- Implement intake normalization\n- Implement artifact planning\n\n## Phase 3: interface and UX\n- Add interactive prompts\n- Add dry-run and diff preview\n- Add file writers with confirmation\n\n## Phase 4: testing and hardening\n- Unit tests for all modules\n- Integration tests with mock provider\n- Secret detection tests\n\n## Phase 5: release readiness\n- README and docs\n- Codex plugin package\n- npm package metadata\n\n## Per-task acceptance criteria\nEach phase must build and pass tests before proceeding.\n\n## Suggested validation command after each phase\n\`npm run build && npm test\``;
    }
    if (target.includes("agent_workflow") || target.includes("workflow")) {
      return `# Agent Workflow\n\n## Files to read first\n1. docs/agentos/PROJECT_BRIEF.md\n2. docs/agentos/PRODUCT_REQUIREMENTS.md\n3. docs/agentos/ARCHITECTURE.md\n4. docs/agentos/IMPLEMENTATION_PLAN.md\n\n## How to plan\n- Read the implementation plan\n- Pick one phase at a time\n- Summarize constraints before coding\n\n## How to implement\n- Follow the stack defined in ARCHITECTURE.md\n- Do not introduce unapproved dependencies\n- Write tests alongside implementation\n\n## How to validate\n- Run \`npm run build\` after changes\n- Run \`npm test\` before finishing\n- Run \`agentos doctor\` on generated outputs\n\n## How to update docs\n- Append decisions to DECISIONS_LOG.md\n- Run \`agentos refine\` for structural changes\n\n## When to ask the user\n- Scope changes\n- New dependency approvals\n- Security or legal concerns\n\n## When not to ask and proceed with a safe default\n- Refactoring internal code\n- Adding tests\n- Fixing typos\n\n## How to log decisions\nAdd a dated entry to DECISIONS_LOG.md with context and rationale.`;
    }
    if (target.includes("acceptance_criteria") || target.includes("acceptance")) {
      return `# Acceptance Criteria\n\n1. CLI builds without errors\n2. Init command generates all required files\n3. Doctor passes after init\n4. Secret detection blocks risky output\n5. Mock provider supports all tests\n6. Generated docs are project-specific\n7. SKILL.md has valid frontmatter\n8. AGENTS.md includes read order and constraints`;
    }
    if (target.includes("decisions_log") || target.includes("decisions log")) {
      return `# Decisions Log

## How to use this log
Append durable architecture, scope, dependency, security, and workflow decisions here with rationale.

## Initial decisions
- **Use TypeScript CLI architecture**
  - Rationale: AgentOS targets Node.js 20+ and benefits from explicit types and npm distribution.
- **Generate docs through structured AI flow**
  - Rationale: The PRD prohibits static markdown templates for generated project docs.`;
    }
    if (target.includes("tech_decisions") || target.includes("technical decisions")) {
      return `# Technical Decisions\n\n- TypeScript for type safety\n- OpenAI Responses API for structured outputs\n- Zod for runtime schema validation\n- Commander.js for CLI routing\n- Vitest for testing\n- No local markdown templates for generated docs`;
    }
    if (target.includes("design_direction") || target.includes("design")) {
      return `# Design Direction\n\n- Clean terminal output with chalk\n- Non-interactive support with --yes and --json\n- Agent-first markdown formatting\n- Consistent heading structure across docs`;
    }
    if (target.includes("security_and_privacy") || target.includes("security")) {
      return `# Security and Privacy\n\n- API keys only via environment variables\n- Secret redaction before sending repo context to AI\n- No secrets in generated markdown\n- .agentosignore for repo scanning exclusions\n- Confirmation before uploading any repo content`;
    }
    if (target.includes("risk_register") || target.includes("risk")) {
      return `# Risk Register\n\n| Risk | Likelihood | Impact | Mitigation |\n|---|---|---|---|\n| API rate limits | Medium | Medium | Retry with backoff; mock provider for tests |\n| Schema drift | Medium | High | Strict Zod validation; versioned schemas |\n| Secret leakage | Low | High | Redaction pipeline; secret detection validator |\n| Over-generated scope | Medium | Medium | Artifact plan review; explicit non-goals |\n`;
    }
    if (target.includes("glossary")) {
      return `# Glossary

## Terms
- **Project Brain**: The AgentOS-generated context package for humans and coding agents.
- **Artifact plan**: The structured list of files AgentOS will generate.
- **Agent Skill**: A portable SKILL.md workflow for compatible coding agents.

## Domain language
- Use precise project-specific names from the generated PRD.

## Ambiguous terms
- Record ambiguous terms here as they are discovered.`;
    }
    return `# Generated Document\n\nThis is a placeholder generated by the mock provider.\n\nSeed: ${system.slice(0, 30)}`;
  }

  async generateStructured<T>(
    request: StructuredGenerationRequest
  ): Promise<T> {
    const system = request.systemPrompt.toLowerCase();
    const user = request.userPrompt.toLowerCase();

    if (system.includes("review") || system.includes("consistency") || user.includes("review")) {
      return {
        fixes: [],
        notes: ["Mock review: no issues detected."],
      } as T;
    }

    if (system.includes("artifact") || system.includes("plan") || user.includes("artifact")) {
      return {
        files: [
          { path: "docs/agentos/PROJECT_BRIEF.md", purpose: "Define the project", sections: ["Summary", "Target users", "Problem", "Proposed solution", "MVP outcome", "Known constraints", "Explicit non-goals", "Open questions", "Agent guidance"], priority: "required", targetAgents: ["codex", "cursor", "generic"] },
          { path: "docs/agentos/PRODUCT_REQUIREMENTS.md", purpose: "Implementation-ready requirements", sections: ["Product overview", "Personas", "User stories", "Functional requirements", "Non-functional requirements", "MVP scope", "Out-of-scope items", "Acceptance criteria", "Edge cases", "Questions for human review"], priority: "required", targetAgents: ["codex", "cursor", "generic"] },
          { path: "docs/agentos/ARCHITECTURE.md", purpose: "Architecture context", sections: ["Architecture summary", "Recommended stack", "Data model assumptions", "Main modules", "Integration points", "State management", "Error handling", "Security considerations", "File structure recommendation", "Architecture tradeoffs", "What not to overbuild"], priority: "required", targetAgents: ["codex", "cursor", "generic"] },
          { path: "docs/agentos/IMPLEMENTATION_PLAN.md", purpose: "Agent-friendly steps", sections: ["Phase 0: setup and verification", "Phase 1: core data model", "Phase 2: core user flow", "Phase 3: interface and UX", "Phase 4: testing and hardening", "Phase 5: release readiness", "Per-task acceptance criteria", "Suggested validation command after each phase"], priority: "required", targetAgents: ["codex", "cursor", "generic"] },
          { path: "docs/agentos/AGENT_WORKFLOW.md", purpose: "Define how agents work in the repo", sections: ["Files to read first", "How to plan", "How to implement", "How to validate", "How to update docs", "When to ask the user", "When not to ask and proceed with a safe default", "How to log decisions"], priority: "required", targetAgents: ["codex", "cursor", "generic"] },
          { path: "docs/agentos/ACCEPTANCE_CRITERIA.md", purpose: "Concrete acceptance criteria", sections: ["Criteria list"], priority: "required", targetAgents: ["codex", "cursor", "generic"] },
          { path: "docs/agentos/TECH_DECISIONS.md", purpose: "Key technical decisions", sections: ["Decisions"], priority: "recommended", targetAgents: ["codex", "cursor", "generic"] },
          { path: "docs/agentos/DESIGN_DIRECTION.md", purpose: "Design constraints", sections: ["Direction"], priority: "recommended", targetAgents: ["codex", "cursor", "generic"] },
          { path: "docs/agentos/SECURITY_AND_PRIVACY.md", purpose: "Security notes", sections: ["Security rules", "Privacy rules"], priority: "required", targetAgents: ["codex", "cursor", "generic"] },
          { path: "docs/agentos/RISK_REGISTER.md", purpose: "Risk tracking", sections: ["Risks table"], priority: "recommended", targetAgents: ["codex", "cursor", "generic"] },
          { path: "docs/agentos/DECISIONS_LOG.md", purpose: "Durable decision log", sections: ["How to use this log", "Initial decisions"], priority: "required", targetAgents: ["codex", "cursor", "generic"] },
          { path: "docs/agentos/GLOSSARY.md", purpose: "Project terminology", sections: ["Terms", "Domain language", "Ambiguous terms"], priority: "recommended", targetAgents: ["codex", "cursor", "generic"] },
        ],
      } as T;
    }

    if (system.includes("normalize") || system.includes("intake") || system.includes("profile") || user.includes("raw idea")) {
      return {
        projectName: "agentos-sample",
        projectKind: "cli-tool",
        targetUsers: ["developers", "technical-founders"],
        problem: "Project setup for AI agents is repetitive and error-prone.",
        proposedSolution: "Generate structured project docs and skills via CLI.",
        platforms: ["node"],
        knownStack: ["typescript", "openai"],
        constraints: ["no-static-templates", "bring-your-own-key"],
        nonGoals: ["hosted-saas", "full-app-scaffolding"],
        risks: ["api-rate-limits", "schema-drift"],
        unknowns: ["default-model-selection"],
        confidence: 0.85,
        followUpQuestions: ["What is the preferred default model?"],
      } as T;
    }

    return { mock: true, seed: `${system.slice(0, 30)}${user.slice(0, 30)}` } as T;
  }

  async testConnection(): Promise<boolean> {
    return true;
  }
}
